fix: allow search on fields number
ForestAdmin/forest-express-sequelize pull request #506
Opened 2020-09-08 16:07 UTC by arnaud-moncel

## Pull Request checklist:

- [X] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [X] Create automatic tests
- [X] Test manually the implemented changes
- [X] Review my own code (indentation, syntax, style, simplicity, readability)
- [ ] Wonder if you can improve the existing code

2020-09-08 16:07 UTC, arnaudbesnier commented
Task linked: [CU-80q41v P3 - Search with field number not working](https://app.clickup.com/t/80q41v)

2020-09-09 12:45 UTC, slimee requested changes
yeah nice shot captain :) 

I've add a small point, please look.

2020-09-09 12:45 UTC, slimee commented on src/services/search-builder.js
> +        }
It seems searching 0 will return no results. 
Using isNaN may help.

2020-09-09 13:02 UTC, slimee approved these changes
🚀

2020-09-09 13:09 UTC, merged