fix(search): handle large numbers in search queries
ForestAdmin/forest-express-sequelize pull request #621
Opened 2021-02-09 11:44 UTC by closingin

## Pull Request checklist:

- [x] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [ ] Create automatic tests
- [x] Test manually the implemented changes
- [x] Review my own code (indentation, syntax, style, simplicity, readability)
- [x] Wonder if you can improve the existing code

2021-02-10 18:59 UTC, arnaudbesnier commented
Task linked: [CU-dyxfm6 P1 - Search - Searching on BIGINT field type returns no results (PostgreSQL)](https://app.clickup.com/t/dyxfm6)

2021-02-11 10:50 UTC, VincentMolinie requested changes
![Capture d’écran 2021-02-11 à 11 49 50](https://user-images.githubusercontent.com/3263749/107627272-55ac9a00-6c5f-11eb-892f-d9e238e9e610.png)
Does not work on my side. I think if you have another column that is not bigint it just crash 🤷

2021-02-11 10:50 UTC, VincentMolinie commented on .eslintrc.js
> +    es2020: true,
Why ?

2021-02-12 08:56 UTC, VincentMolinie submitted a review, later dismissed

2021-02-12 08:57 UTC, VincentMolinie commented
A little test would be appreciated, anyway codeclimate won't let you merge if you don't 😉

2021-02-18 23:08 UTC, closingin commented
It is currently impossible to test this fix correctly, as the [library](https://github.com/domasx2/sequelize-fixtures) we use to load fixtures does not support large numbers. Its reader [here](https://github.com/domasx2/sequelize-fixtures/blob/master/lib/reader.js#L16) relies on `JSON.parse`, which is not compatible with numbers over `MAX_SAFE_INTEGER`.

Using [`json-bigint`](https://www.npmjs.com/package/json-bigint) would fix it, but the project seems unmaintained. Maybe we should fork?

If not, then we'll have to merge without testing. I still pushed the required tests even though they do not work.

2021-02-19 08:33 UTC, VincentMolinie approved these changes

2021-02-19 13:45 UTC, VincentMolinie approved these changes

2021-02-19 13:58 UTC, closingin commented
Someone needs to approve this PR on CodeClimate. Based on the current codebase, I'm kinda forced to keep it as it is right now.

2021-02-19 13:59 UTC, merged