refactor: rewrite as class and use query-options generator on value-stat-getter
ForestAdmin/forest-express-sequelize pull request #714
Opened 2021-05-04 13:06 UTC by romain-gilliotte

## Pull Request checklist:

- [ ] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [ ] Create automatic tests
- [ ] Test manually the implemented changes
- [ ] Review my own code (indentation, syntax, style, simplicity, readability)
- [ ] Wonder if you can improve the existing code

2021-05-04 16:01 UTC, VincentMolinie requested changes

2021-05-05 07:33 UTC, VincentMolinie requested changes

2021-05-05 07:33 UTC, VincentMolinie commented on src/services/value-stat-getter.js
> +      ? options.include.map((includeProps) => ({ ...includeProps, attributes: [] }))
this is still a shortcut

2021-05-05 07:33 UTC, VincentMolinie commented on src/services/value-stat-getter.js
> +      ? options.include.map((includeProps) => ({ ...includeProps, attributes: [] }))
includedModel ? 🤔  
includedRelation ?

2021-05-05 07:54 UTC, romain-gilliotte commented on src/services/value-stat-getter.js
> +      ? options.include.map((includeProps) => ({ ...includeProps, attributes: [] }))
ca sera includeProperties

2021-05-05 08:01 UTC, VincentMolinie approved these changes

2021-05-05 08:03 UTC, merged